let BOOKS = [
  {
    id: 1,
    title: "خواجه تاجدار",
    author: "ژان گور",
    publishedDate: 2007,
    language: "persian",
    genre: "تاریخ",
    price:250000,
    imgSrc: "../images/item-images/1.jpg",
  },
  {
    id: 2,
    title: "ضیافت",
    author: "افلاطون",
    publishedDate: 385,
    language: "greek",
    genre: "فلسفه",
    price:350000,
    imgSrc: "../images/item-images/2.jpg",
  },
  {
    id: 3,
    title: "منطق الطیر",
    author: "عطار",
    publishedDate: 1177,
    language: "persian",
    genre: "شعر",
    price:550000,
    imgSrc: "../images/item-images/3.jpg",
  },
  {
    id: 4,
    title: "مثنوی معنوی",
    author: "مولوی",
    publishedDate: 1258,
    language: "persian",
    genre: "شعر",
    price:200000,
    imgSrc: "../images/item-images/4.jpg",
  },
  {
    id: 5,
    title: "دیوان حافظ",
    author: "حافظ",
    publishedDate: 1200,
    language: "persian",
    genre: "شعر",
    price:250000,
    imgSrc: "../images/item-images/5.jpg",
  },
  {
    id: 6,
    title: "رومیو و جولیت",
    author: "ویلیام شکسپیر",
    publishedDate: 1595,
    language: "english",
    genre: "عاشقانه",
    price:820000,
    imgSrc: "../images/item-images/6.jpg",
  },
  {
    id: 7,
    title: "ویس و رامین",
    author: "فخرالدین اسعد گرگانی",
    publishedDate: 1054,
    language: "persian",
    genre: "عاشقانه",
    price:375000,
    imgSrc: "../images/item-images/7.jpg",
  },
  {
    id: 8,
    title: "گلستان",
    author: "سعدی",
    publishedDate: 1258,
    language: "persian",
    genre: "شعر",
    price:512000,
    imgSrc: "../images/item-images/8.jpg",
  },
  {
    id: 9,
    title: "بوستان",
    author: "سعدی",
    publishedDate: 1257,
    language: "persian",
    genre: "شعر",
    price:210000,
    imgSrc: "../images/item-images/9.jpg",
  },
  {
    id: 10,
    title: "گلشن راز",
    author: "شیخ محمود شبستری",
    publishedDate: 1311,
    language: "persian",
    genre: "شعر",
    price:610000,
    imgSrc: "../images/item-images/10.jpg",
  },
  {
    id: 11,
    title: "لیلی و مجنون",
    author: "نظامی",
    publishedDate: 1188,
    language: "persian",
    genre: "عاشقانه",
    price:75000,
    imgSrc: "../images/item-images/11.jpg",
  },
  {
    id: 12,
    title: "شاهنامه",
    author: "فردوسی",
    publishedDate: 1010,
    language: "persian",
    genre: "شعر",
    price:100000,
    imgSrc: "../images/item-images/12.jpg",
  },
  {
    id: 13,
    title: "ایلیاد",
    author: "هومر",
    publishedDate: 762,
    language: "greek",
    genre: "شعر",
    price:250000,
    imgSrc: "../images/item-images/13.jpg",
  },
  {
    id: 14,
    title: "اودیسه",
    author: "هومر",
    publishedDate: 725,
    language: "greek",
    genre: "شعر",
    price:450000,
    imgSrc: "../images/item-images/14.jpg",
  },
  {
    id: 15,
    title: "هملت",
    author: "ویلیام شکسپیر",
    publishedDate: 1609,
    language: "greek",
    genre: "درام",
    price:370000,
    imgSrc: "../images/item-images/15.jpg",
  },
  {
    id: 16,
    title: "دن کیشوت",
    author: "میگل دسروانتس",
    publishedDate: 1605,
    language: "spanish",
    genre: "درام",
    price:950000,
    imgSrc: "../images/item-images/16.jpg",
  },
];
let YOURLAB = [];



